apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
  namespace: hipster-shop
  annotations:
    dt.owner: "hipster-shop"
    resource-optimization.dynatrace.com/enabled: "true"
    resource-optimization.dynatrace.com/github-repo: "github.com/Observe-Resolve/resource-optimization"
    resource-optimization.dynatrace.com/github-path: "hipster-shop/cartservice.yaml"
    resource-optimization.dynatrace.com/github-branch: "master"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
      annotations:
        dt.owner: "hipster-shop"
        resource-optimization.dynatrace.com/enabled: "true"
        resource-optimization.dynatrace.com/github-repo: "github.com/Observe-Resolve/resource-optimization"
        resource-optimization.dynatrace.com/github-path: "hipster-shop/cartservice.yaml"
        resource-optimization.dynatrace.com/github-branch: "master"
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: us-central1-docker.pkg.dev/google-samples/microservices-demo/cartservice:v0.10.4
        ports:
        - containerPort: 7070
          name: grpc
        env:
        - name: REDIS_ADDR
          value: "redis-cart:6379"
        resources:
          requests:
            cpu: 300m
            memory: 512Mi
          limits:
            cpu: 600m
            memory: 1Gi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        livenessProbe:
          grpc:
            port: 7070
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          grpc:
            port: 7070
          initialDelaySeconds: 5
          periodSeconds: 10