apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - emailservice.yaml
  - checkoutservice.yaml
  - recommendationservice.yaml
  - frontend.yaml
  - paymentservice.yaml
  - productcatalogservice.yaml
  - cartservice.yaml
  - loadgenerator.yaml
  - currencyservice.yaml
  - shippingservice.yaml
  - adservice.yaml
  - redis-cart.yaml
  - emailservice_svc.yaml
  - checkoutservice_svc.yaml
  - recommendationservice_svc.yaml
  - frontend_svc.yaml
  - paymentservice_svc.yaml
  - productcatalogservice_svc.yaml
  - cartservice_svc.yaml
  - currencyservice_svc.yaml
  - shippingservice_svc.yaml
  - adservice_svc.yaml
  - redis-cart_svc.yaml
