apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice
  namespace: hipster-shop
spec:
  type: ClusterIP
  selector:
    app: productcatalogservice
  ports:
  - port: 3550
    targetPort: 3550
    protocol: TCP
    name: grpc
